"""Add user_id to Photo model

Revision ID: 097fab69af08
Revises: 377053f32330
Create Date: 2025-05-13 19:34:26.382174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097fab69af08'
down_revision = '377053f32330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Time(),
               existing_nullable=False)

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('upload_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('upload_time')
        batch_op.drop_column('filename')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
